-- Rollback snapshot ЕГЭ flatten, 2026-06-04T14:30:35.896535
-- Применять при необходимости отката внутри BEGIN;...COMMIT;
BEGIN;

-- 1. Восстановить удалённые курсы-навигаторы
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (113, 'Навигатор по заданию 1 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:40:29.104992+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-1-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (114, 'Навигатор по заданию 2 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:40:37.295834+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-2-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (115, 'Навигатор по заданию 3 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:40:45.524555+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-3-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (116, 'Навигатор по заданию 4 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:40:53.724824+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-4-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (117, 'Навигатор по заданию 5 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:01.943514+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-5-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (118, 'Навигатор по заданию 6 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:10.154557+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-6-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (119, 'Навигатор по заданию 7 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:18.350554+05:00'::timestamptz, false, 'wp:zadanie-7-ege-po-informatike-kodirovanie-razlichnyh-vidov-informatsii', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (120, 'Навигатор по заданию 8 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:26.574752+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-8-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (121, 'Навигатор по заданию 9 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:34.808660+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-9-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (122, 'Навигатор по заданию 10 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:38.900837+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-10-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (123, 'Навигатор по заданию 11 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:42.979551+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-11-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (124, 'Навигатор по заданию 12 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:47.076720+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-12-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (125, 'Навигатор по заданию 13 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:51.149046+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-13-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (126, 'Навигатор по заданию 14 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:55.263637+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-14-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (127, 'Навигатор по заданию 15 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:41:59.366028+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-15-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (128, 'Навигатор по заданию 16 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:03.472875+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-16-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (129, 'Навигатор по заданию 17 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:07.570195+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-17-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (130, 'Навигатор по заданию 18 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:11.691494+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-18-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (131, 'Навигатор по заданию 19-21 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:15.807819+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-19-21-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (132, 'Навигатор по заданию 22 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:19.911590+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-22-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (133, 'Навигатор по заданию 23 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:23.994101+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-23-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (134, 'Навигатор по заданию 24 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:28.088848+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-24-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (135, 'Навигатор по заданию 25 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:32.209388+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-25-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (136, 'Навигатор по заданию 26 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:36.301197+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-26-ege', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO courses (id, title, access_level, description, created_at, is_required, course_uid, is_public_demo) VALUES (137, 'Навигатор по заданию 27 ЕГЭ', 'self_guided'::access_level, NULL, '2026-04-14 00:42:40.376377+05:00'::timestamptz, false, 'wp:navigator-po-zadaniyu-27-ege', false) ON CONFLICT (id) DO NOTHING;

-- 2. Восстановить привязку материалов (course_id, order_position)
UPDATE materials SET course_id=165, order_position=0 WHERE id=310;
UPDATE materials SET course_id=165, order_position=1 WHERE id=311;
UPDATE materials SET course_id=165, order_position=2 WHERE id=312;
UPDATE materials SET course_id=165, order_position=3 WHERE id=313;
UPDATE materials SET course_id=165, order_position=4 WHERE id=314;
UPDATE materials SET course_id=165, order_position=5 WHERE id=315;
UPDATE materials SET course_id=165, order_position=6 WHERE id=316;
UPDATE materials SET course_id=165, order_position=7 WHERE id=317;
UPDATE materials SET course_id=138, order_position=0 WHERE id=318;
UPDATE materials SET course_id=138, order_position=1 WHERE id=319;
UPDATE materials SET course_id=138, order_position=2 WHERE id=320;
UPDATE materials SET course_id=138, order_position=3 WHERE id=321;
UPDATE materials SET course_id=138, order_position=4 WHERE id=322;
UPDATE materials SET course_id=138, order_position=5 WHERE id=323;
UPDATE materials SET course_id=138, order_position=6 WHERE id=324;
UPDATE materials SET course_id=161, order_position=0 WHERE id=325;
UPDATE materials SET course_id=161, order_position=1 WHERE id=326;
UPDATE materials SET course_id=161, order_position=2 WHERE id=327;
UPDATE materials SET course_id=161, order_position=3 WHERE id=328;
UPDATE materials SET course_id=161, order_position=4 WHERE id=329;
UPDATE materials SET course_id=161, order_position=5 WHERE id=330;
UPDATE materials SET course_id=161, order_position=6 WHERE id=331;
UPDATE materials SET course_id=161, order_position=7 WHERE id=332;
UPDATE materials SET course_id=161, order_position=8 WHERE id=333;
UPDATE materials SET course_id=164, order_position=0 WHERE id=334;
UPDATE materials SET course_id=164, order_position=1 WHERE id=335;
UPDATE materials SET course_id=164, order_position=2 WHERE id=336;
UPDATE materials SET course_id=164, order_position=3 WHERE id=337;
UPDATE materials SET course_id=164, order_position=4 WHERE id=338;
UPDATE materials SET course_id=164, order_position=5 WHERE id=339;
UPDATE materials SET course_id=164, order_position=6 WHERE id=340;
UPDATE materials SET course_id=164, order_position=7 WHERE id=341;
UPDATE materials SET course_id=164, order_position=8 WHERE id=342;
UPDATE materials SET course_id=164, order_position=9 WHERE id=343;
UPDATE materials SET course_id=164, order_position=10 WHERE id=344;
UPDATE materials SET course_id=164, order_position=11 WHERE id=345;
UPDATE materials SET course_id=164, order_position=12 WHERE id=346;
UPDATE materials SET course_id=164, order_position=13 WHERE id=347;
UPDATE materials SET course_id=164, order_position=14 WHERE id=348;
UPDATE materials SET course_id=164, order_position=15 WHERE id=349;
UPDATE materials SET course_id=164, order_position=16 WHERE id=350;
UPDATE materials SET course_id=164, order_position=17 WHERE id=351;
UPDATE materials SET course_id=164, order_position=18 WHERE id=352;
UPDATE materials SET course_id=139, order_position=0 WHERE id=353;
UPDATE materials SET course_id=139, order_position=1 WHERE id=354;
UPDATE materials SET course_id=139, order_position=2 WHERE id=355;
UPDATE materials SET course_id=139, order_position=3 WHERE id=356;
UPDATE materials SET course_id=139, order_position=4 WHERE id=357;
UPDATE materials SET course_id=140, order_position=0 WHERE id=358;
UPDATE materials SET course_id=140, order_position=1 WHERE id=359;
UPDATE materials SET course_id=140, order_position=2 WHERE id=360;
UPDATE materials SET course_id=140, order_position=3 WHERE id=361;
UPDATE materials SET course_id=140, order_position=4 WHERE id=362;
UPDATE materials SET course_id=140, order_position=5 WHERE id=363;
UPDATE materials SET course_id=140, order_position=6 WHERE id=364;
UPDATE materials SET course_id=140, order_position=7 WHERE id=365;
UPDATE materials SET course_id=141, order_position=0 WHERE id=366;
UPDATE materials SET course_id=141, order_position=1 WHERE id=367;
UPDATE materials SET course_id=141, order_position=2 WHERE id=368;
UPDATE materials SET course_id=162, order_position=0 WHERE id=369;
UPDATE materials SET course_id=162, order_position=1 WHERE id=370;
UPDATE materials SET course_id=162, order_position=2 WHERE id=371;
UPDATE materials SET course_id=162, order_position=3 WHERE id=372;
UPDATE materials SET course_id=163, order_position=0 WHERE id=373;
UPDATE materials SET course_id=163, order_position=1 WHERE id=374;
UPDATE materials SET course_id=163, order_position=2 WHERE id=375;
UPDATE materials SET course_id=163, order_position=3 WHERE id=376;
UPDATE materials SET course_id=163, order_position=4 WHERE id=377;
UPDATE materials SET course_id=142, order_position=0 WHERE id=378;
UPDATE materials SET course_id=142, order_position=1 WHERE id=379;
UPDATE materials SET course_id=142, order_position=2 WHERE id=380;
UPDATE materials SET course_id=142, order_position=3 WHERE id=381;
UPDATE materials SET course_id=143, order_position=0 WHERE id=382;
UPDATE materials SET course_id=143, order_position=1 WHERE id=383;
UPDATE materials SET course_id=143, order_position=2 WHERE id=384;
UPDATE materials SET course_id=144, order_position=0 WHERE id=385;
UPDATE materials SET course_id=144, order_position=1 WHERE id=386;
UPDATE materials SET course_id=145, order_position=0 WHERE id=387;
UPDATE materials SET course_id=145, order_position=1 WHERE id=388;
UPDATE materials SET course_id=146, order_position=0 WHERE id=389;
UPDATE materials SET course_id=146, order_position=1 WHERE id=390;
UPDATE materials SET course_id=147, order_position=0 WHERE id=391;
UPDATE materials SET course_id=147, order_position=1 WHERE id=392;
UPDATE materials SET course_id=148, order_position=0 WHERE id=393;
UPDATE materials SET course_id=148, order_position=1 WHERE id=394;
UPDATE materials SET course_id=148, order_position=2 WHERE id=395;
UPDATE materials SET course_id=148, order_position=3 WHERE id=396;
UPDATE materials SET course_id=148, order_position=4 WHERE id=397;
UPDATE materials SET course_id=148, order_position=5 WHERE id=398;
UPDATE materials SET course_id=148, order_position=6 WHERE id=399;
UPDATE materials SET course_id=148, order_position=7 WHERE id=400;
UPDATE materials SET course_id=148, order_position=8 WHERE id=401;
UPDATE materials SET course_id=148, order_position=9 WHERE id=402;
UPDATE materials SET course_id=148, order_position=10 WHERE id=403;
UPDATE materials SET course_id=149, order_position=0 WHERE id=404;
UPDATE materials SET course_id=149, order_position=1 WHERE id=405;
UPDATE materials SET course_id=150, order_position=0 WHERE id=406;
UPDATE materials SET course_id=151, order_position=0 WHERE id=407;
UPDATE materials SET course_id=151, order_position=1 WHERE id=408;
UPDATE materials SET course_id=152, order_position=0 WHERE id=409;
UPDATE materials SET course_id=152, order_position=1 WHERE id=410;
UPDATE materials SET course_id=153, order_position=0 WHERE id=411;
UPDATE materials SET course_id=154, order_position=0 WHERE id=412;
UPDATE materials SET course_id=154, order_position=1 WHERE id=413;
UPDATE materials SET course_id=154, order_position=2 WHERE id=414;
UPDATE materials SET course_id=155, order_position=0 WHERE id=415;
UPDATE materials SET course_id=155, order_position=1 WHERE id=416;
UPDATE materials SET course_id=155, order_position=2 WHERE id=417;
UPDATE materials SET course_id=155, order_position=3 WHERE id=418;
UPDATE materials SET course_id=155, order_position=4 WHERE id=419;
UPDATE materials SET course_id=156, order_position=0 WHERE id=420;
UPDATE materials SET course_id=156, order_position=1 WHERE id=421;
UPDATE materials SET course_id=156, order_position=2 WHERE id=422;
UPDATE materials SET course_id=156, order_position=3 WHERE id=423;
UPDATE materials SET course_id=156, order_position=4 WHERE id=424;
UPDATE materials SET course_id=156, order_position=5 WHERE id=425;
UPDATE materials SET course_id=157, order_position=0 WHERE id=426;
UPDATE materials SET course_id=157, order_position=1 WHERE id=427;
UPDATE materials SET course_id=157, order_position=2 WHERE id=428;
UPDATE materials SET course_id=157, order_position=3 WHERE id=429;
UPDATE materials SET course_id=157, order_position=4 WHERE id=430;
UPDATE materials SET course_id=157, order_position=5 WHERE id=431;
UPDATE materials SET course_id=157, order_position=6 WHERE id=432;
UPDATE materials SET course_id=157, order_position=7 WHERE id=433;
UPDATE materials SET course_id=157, order_position=8 WHERE id=434;
UPDATE materials SET course_id=158, order_position=0 WHERE id=435;
UPDATE materials SET course_id=158, order_position=1 WHERE id=436;
UPDATE materials SET course_id=158, order_position=2 WHERE id=437;
UPDATE materials SET course_id=158, order_position=3 WHERE id=438;
UPDATE materials SET course_id=159, order_position=0 WHERE id=439;
UPDATE materials SET course_id=159, order_position=1 WHERE id=440;
UPDATE materials SET course_id=159, order_position=2 WHERE id=441;
UPDATE materials SET course_id=159, order_position=3 WHERE id=442;
UPDATE materials SET course_id=159, order_position=4 WHERE id=443;
UPDATE materials SET course_id=160, order_position=0 WHERE id=444;
UPDATE materials SET course_id=160, order_position=1 WHERE id=445;
UPDATE materials SET course_id=160, order_position=2 WHERE id=446;
UPDATE materials SET course_id=113, order_position=0 WHERE id=540;
UPDATE materials SET course_id=113, order_position=1 WHERE id=541;
UPDATE materials SET course_id=113, order_position=2 WHERE id=542;
UPDATE materials SET course_id=113, order_position=3 WHERE id=543;
UPDATE materials SET course_id=123, order_position=0 WHERE id=544;
UPDATE materials SET course_id=123, order_position=1 WHERE id=545;
UPDATE materials SET course_id=123, order_position=2 WHERE id=546;
UPDATE materials SET course_id=124, order_position=0 WHERE id=547;
UPDATE materials SET course_id=124, order_position=1 WHERE id=548;
UPDATE materials SET course_id=125, order_position=0 WHERE id=549;
UPDATE materials SET course_id=125, order_position=1 WHERE id=550;
UPDATE materials SET course_id=125, order_position=2 WHERE id=551;
UPDATE materials SET course_id=125, order_position=3 WHERE id=552;
UPDATE materials SET course_id=125, order_position=4 WHERE id=553;
UPDATE materials SET course_id=125, order_position=5 WHERE id=554;
UPDATE materials SET course_id=125, order_position=6 WHERE id=555;
UPDATE materials SET course_id=125, order_position=7 WHERE id=556;
UPDATE materials SET course_id=125, order_position=8 WHERE id=557;
UPDATE materials SET course_id=125, order_position=9 WHERE id=558;
UPDATE materials SET course_id=125, order_position=10 WHERE id=559;
UPDATE materials SET course_id=125, order_position=11 WHERE id=560;
UPDATE materials SET course_id=125, order_position=12 WHERE id=561;
UPDATE materials SET course_id=125, order_position=13 WHERE id=562;
UPDATE materials SET course_id=125, order_position=14 WHERE id=563;
UPDATE materials SET course_id=125, order_position=15 WHERE id=564;
UPDATE materials SET course_id=126, order_position=0 WHERE id=565;
UPDATE materials SET course_id=126, order_position=1 WHERE id=566;
UPDATE materials SET course_id=126, order_position=2 WHERE id=567;
UPDATE materials SET course_id=126, order_position=3 WHERE id=568;
UPDATE materials SET course_id=126, order_position=4 WHERE id=569;
UPDATE materials SET course_id=126, order_position=5 WHERE id=570;
UPDATE materials SET course_id=126, order_position=6 WHERE id=571;
UPDATE materials SET course_id=126, order_position=7 WHERE id=572;
UPDATE materials SET course_id=126, order_position=8 WHERE id=573;
UPDATE materials SET course_id=126, order_position=9 WHERE id=574;
UPDATE materials SET course_id=126, order_position=10 WHERE id=575;
UPDATE materials SET course_id=126, order_position=11 WHERE id=576;
UPDATE materials SET course_id=126, order_position=12 WHERE id=577;
UPDATE materials SET course_id=127, order_position=0 WHERE id=578;
UPDATE materials SET course_id=127, order_position=1 WHERE id=579;
UPDATE materials SET course_id=127, order_position=2 WHERE id=580;
UPDATE materials SET course_id=127, order_position=3 WHERE id=581;
UPDATE materials SET course_id=127, order_position=4 WHERE id=582;
UPDATE materials SET course_id=127, order_position=5 WHERE id=583;
UPDATE materials SET course_id=128, order_position=0 WHERE id=584;
UPDATE materials SET course_id=128, order_position=1 WHERE id=585;
UPDATE materials SET course_id=128, order_position=2 WHERE id=586;
UPDATE materials SET course_id=129, order_position=0 WHERE id=587;
UPDATE materials SET course_id=129, order_position=1 WHERE id=588;
UPDATE materials SET course_id=129, order_position=2 WHERE id=589;
UPDATE materials SET course_id=129, order_position=3 WHERE id=590;
UPDATE materials SET course_id=129, order_position=4 WHERE id=591;
UPDATE materials SET course_id=129, order_position=5 WHERE id=592;
UPDATE materials SET course_id=130, order_position=0 WHERE id=593;
UPDATE materials SET course_id=130, order_position=1 WHERE id=594;
UPDATE materials SET course_id=130, order_position=2 WHERE id=595;
UPDATE materials SET course_id=131, order_position=0 WHERE id=596;
UPDATE materials SET course_id=131, order_position=1 WHERE id=597;
UPDATE materials SET course_id=131, order_position=2 WHERE id=598;
UPDATE materials SET course_id=131, order_position=3 WHERE id=599;
UPDATE materials SET course_id=131, order_position=4 WHERE id=600;
UPDATE materials SET course_id=131, order_position=5 WHERE id=601;
UPDATE materials SET course_id=131, order_position=6 WHERE id=602;
UPDATE materials SET course_id=131, order_position=7 WHERE id=603;
UPDATE materials SET course_id=131, order_position=8 WHERE id=604;
UPDATE materials SET course_id=114, order_position=0 WHERE id=605;
UPDATE materials SET course_id=114, order_position=1 WHERE id=606;
UPDATE materials SET course_id=114, order_position=2 WHERE id=607;
UPDATE materials SET course_id=114, order_position=3 WHERE id=608;
UPDATE materials SET course_id=132, order_position=0 WHERE id=609;
UPDATE materials SET course_id=132, order_position=1 WHERE id=610;
UPDATE materials SET course_id=133, order_position=0 WHERE id=611;
UPDATE materials SET course_id=133, order_position=1 WHERE id=612;
UPDATE materials SET course_id=133, order_position=2 WHERE id=613;
UPDATE materials SET course_id=133, order_position=3 WHERE id=614;
UPDATE materials SET course_id=133, order_position=4 WHERE id=615;
UPDATE materials SET course_id=133, order_position=5 WHERE id=616;
UPDATE materials SET course_id=134, order_position=0 WHERE id=617;
UPDATE materials SET course_id=134, order_position=1 WHERE id=618;
UPDATE materials SET course_id=134, order_position=2 WHERE id=619;
UPDATE materials SET course_id=134, order_position=3 WHERE id=620;
UPDATE materials SET course_id=134, order_position=4 WHERE id=621;
UPDATE materials SET course_id=134, order_position=5 WHERE id=622;
UPDATE materials SET course_id=134, order_position=6 WHERE id=623;
UPDATE materials SET course_id=134, order_position=7 WHERE id=624;
UPDATE materials SET course_id=134, order_position=8 WHERE id=625;
UPDATE materials SET course_id=134, order_position=9 WHERE id=626;
UPDATE materials SET course_id=134, order_position=10 WHERE id=627;
UPDATE materials SET course_id=135, order_position=0 WHERE id=628;
UPDATE materials SET course_id=135, order_position=1 WHERE id=629;
UPDATE materials SET course_id=135, order_position=2 WHERE id=630;
UPDATE materials SET course_id=136, order_position=0 WHERE id=631;
UPDATE materials SET course_id=136, order_position=1 WHERE id=632;
UPDATE materials SET course_id=136, order_position=2 WHERE id=633;
UPDATE materials SET course_id=115, order_position=0 WHERE id=634;
UPDATE materials SET course_id=115, order_position=1 WHERE id=635;
UPDATE materials SET course_id=115, order_position=2 WHERE id=636;
UPDATE materials SET course_id=115, order_position=3 WHERE id=637;
UPDATE materials SET course_id=115, order_position=4 WHERE id=638;
UPDATE materials SET course_id=116, order_position=0 WHERE id=639;
UPDATE materials SET course_id=116, order_position=1 WHERE id=640;
UPDATE materials SET course_id=116, order_position=2 WHERE id=641;
UPDATE materials SET course_id=117, order_position=0 WHERE id=642;
UPDATE materials SET course_id=117, order_position=1 WHERE id=643;
UPDATE materials SET course_id=117, order_position=2 WHERE id=644;
UPDATE materials SET course_id=117, order_position=3 WHERE id=645;
UPDATE materials SET course_id=117, order_position=4 WHERE id=646;
UPDATE materials SET course_id=117, order_position=5 WHERE id=647;
UPDATE materials SET course_id=117, order_position=6 WHERE id=648;
UPDATE materials SET course_id=117, order_position=7 WHERE id=649;
UPDATE materials SET course_id=118, order_position=0 WHERE id=650;
UPDATE materials SET course_id=118, order_position=1 WHERE id=651;
UPDATE materials SET course_id=118, order_position=2 WHERE id=652;
UPDATE materials SET course_id=120, order_position=0 WHERE id=653;
UPDATE materials SET course_id=120, order_position=1 WHERE id=654;
UPDATE materials SET course_id=120, order_position=2 WHERE id=655;
UPDATE materials SET course_id=120, order_position=3 WHERE id=656;
UPDATE materials SET course_id=121, order_position=0 WHERE id=657;
UPDATE materials SET course_id=121, order_position=1 WHERE id=658;
UPDATE materials SET course_id=121, order_position=2 WHERE id=659;
UPDATE materials SET course_id=121, order_position=3 WHERE id=660;
UPDATE materials SET course_id=121, order_position=4 WHERE id=661;
UPDATE materials SET course_id=121, order_position=5 WHERE id=662;
UPDATE materials SET course_id=121, order_position=6 WHERE id=663;
UPDATE materials SET course_id=121, order_position=7 WHERE id=664;
UPDATE materials SET course_id=119, order_position=0 WHERE id=665;
UPDATE materials SET course_id=119, order_position=1 WHERE id=666;
UPDATE materials SET course_id=119, order_position=2 WHERE id=667;
UPDATE materials SET course_id=119, order_position=3 WHERE id=668;
UPDATE materials SET course_id=119, order_position=4 WHERE id=669;

-- 3. Восстановить course_parents
DELETE FROM course_parents WHERE course_id BETWEEN 113 AND 165;
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (113, 112, 2);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (114, 112, 3);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (115, 112, 4);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (116, 112, 5);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (117, 112, 6);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (118, 112, 7);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (119, 112, 8);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (120, 112, 9);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (121, 112, 10);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (122, 112, 11);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (123, 112, 12);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (124, 112, 13);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (125, 112, 14);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (126, 112, 15);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (127, 112, 16);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (128, 112, 17);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (129, 112, 18);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (130, 112, 19);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (131, 112, 20);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (132, 112, 21);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (133, 112, 22);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (134, 112, 23);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (135, 112, 24);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (136, 112, 25);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (137, 112, 26);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (138, 115, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (139, 125, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (140, 113, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (141, 122, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (142, 126, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (143, 127, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (144, 128, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (145, 129, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (146, 130, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (147, 131, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (148, 114, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (149, 132, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (150, 133, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (151, 134, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (152, 135, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (153, 136, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (154, 137, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (155, 116, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (156, 117, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (157, 118, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (158, 119, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (159, 120, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (160, 124, 1);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (161, 121, 2);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (162, 123, 2);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (163, 124, 2);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (164, 121, 3);
INSERT INTO course_parents (course_id, parent_course_id, order_number) VALUES (165, 118, 6);

-- COMMIT;  -- снять комментарий после проверки
